---
- name: copy over the splunk installation deb
  sudo_user: root
  copy: src={{ splunk_filename }} dest=/tmp

- name: copy over storm credentials deb
  sudo_user: root 
  copy: src={{ credentials_filename }} dest=/tmp

- name: install splunk with dpkg
  sudo_user: root
  command: dpkg -i /tmp/{{ splunk_filename }} creates=/opt/splunkforwarder

  # Gives Splunk permission to read certain log files (esp. nginx)
- name: add splunk user to the adm group
  sudo_user: root
  user: name=splunk group=adm

  # Fixes side effects of earlier Splunk tasks that ran as root
- name: make splunk the owner of splunk directory
  sudo_user: root
  file: path=/opt/splunkforwarder state=directory 
        owner=splunk group=splunk recurse=yes

- name: splunk license
  command: /opt/splunkforwarder/bin/splunk start --accept-license creates=/opt/splunkforwarder/etc/users/splunk-system-user

- name: setup to start at boot
  sudo_user: root
  command: /opt/splunkforwarder/bin/splunk enable boot-start

- name: Install forwarder credentials
  command: /opt/splunkforwarder/bin/splunk install app /tmp/{{ credentials_filename }}  -auth admin:changeme
  ignore_errors: yes

- name: add monitor for app
  command: /opt/splunkforwarder/bin/splunk add monitor {{ APP_DIR }}/log
  ignore_errors: yes

- name: add monitor for nginx
  command: /opt/splunkforwarder/bin/splunk add monitor /var/log/nginx
  ignore_errors: yes

  # Sometimes we need to stop forwarding to a given Storm project and
  # switch to another one. The next two tasks will override the
  # parameters defined in the .spl credentials package with those from
  # our group vars.

- name: ensure 'default' section exists in inputs.conf
  lineinfile: dest={{ storm_app_dir }}/local/inputs.conf 
              line=[default] state=present backup=yes

- name: override storm api token
  ini_file: dest={{ storm_app_dir }}/local/inputs.conf 
            section=default state=present backup=yes
            option=_storm_api_token value={{ STORM_API_TOKEN }}
  when: STORM_API_TOKEN is defined

- name: override storm project ID
  ini_file: dest={{ storm_app_dir }}/local/inputs.conf
            section=default state=present backup=yes
            option=_storm_project_id value={{ STORM_PROJECT_ID }}
  when: STORM_PROJECT_ID is defined

- name: restart forwarder
  command: /opt/splunkforwarder/bin/splunk restart
