---
- name: copy over the splunk installation deb
  sudo_user: root
  copy: src={{ splunk_filename }} dest=/tmp

- name: install splunk with dpkg
  sudo_user: root
  command: dpkg -i /tmp/{{ splunk_filename }} creates=/opt/splunkforwarder

  # Gives Splunk permission to read certain log files (esp. nginx)
- name: add splunk user to the adm group
  sudo_user: root
  user: name=splunk group=adm

- name: add splunk credential files
  copy: src=splunkclouduf.spl dest=/opt/splunkclouduf.spl

- name: splunk license
  command: /opt/splunkforwarder/bin/splunk start --accept-license creates=/opt/splunkforwarder/etc/users/splunk-system-user

- name: setting up forwarder credentials
  command: /opt/splunkforwarder/bin/splunk install app /opt/splunkclouduf.spl -auth admin:changeme

  # Fixes side effects of earlier Splunk tasks that ran as root
- name: make splunk the owner of splunk directory
  sudo_user: root
  file: path=/opt/splunkforwarder state=directory 
        owner=splunk group=splunk recurse=yes
