---
# tasks file for app_server

- name: Install system packages
  apt: pkg={{ item }} state=present
  with_items:
    - default-jre
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libxslt1-dev
    - build-essential
    - python-dev
    - python-boto
    - python-pip
    - authbind
    - supervisor
    - postfix
    - mercurial
    - rabbitmq-server

- name: Ensure pip is up-to-date
  command: pip install --upgrade pip

- name: Install application requirements
  pip: requirements=/requirements.txt
  tags:
    - pip

- name: Allow app to bind to port 80
  file: path=/etc/authbind/byport/80 state=touch
        owner={{ APP_USER }} group={{ APP_USER }} mode=755

- name: Write supervisord.conf
  template: dest=/etc/supervisor/supervisord.conf
            src=supervisord.conf.j2
            backup=yes 

- name: Set supervisor to run on boot
  service: name=supervisor enabled=yes

- name: Link to app-specific supervisor configuration
  file: >
    src={{ APP_DIR }}/supervisord.conf
    dest=/etc/supervisor/conf.d/{{ APP_NAME }}.conf
    state=link force=yes

- name: Create nginx site configuration
  template: src=nginx.site.j2 
            dest=/etc/nginx/sites-available/{{ APP_NAME }}
  notify: 
    - reload nginx
  tags:
    - nginx_conf

- name: Create link to enable nginx site
  file: path=/etc/nginx/sites-enabled/{{ APP_NAME }} 
        src=/etc/nginx/sites-available/{{ APP_NAME }}
        state=link
  notify:
    - reload nginx

- name: Write logrotate.conf
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/{{ APP_NAME }}
            backup=yes

- name: Schedule log rotation
  cron: name="rotate {{ APP_NAME }} logs" special_time=hourly
        job="/usr/sbin/logrotate /etc/logrotate.d/{{ APP_NAME }}"


