---
# tasks file for app_server

- name: Write supervisord.conf
  template: dest=/etc/supervisor/supervisord.conf
            src=supervisord.conf.j2
            backup=yes 

- name: Set supervisor to run on boot
  service: name=supervisor enabled=yes

- name: Link to app-specific supervisor configuration
  file: >
    src=/root/config/supervisord.conf
    dest=/etc/supervisor/conf.d/{{ APP_NAME }}.conf
    state=link force=yes

#- name: Write logrotate.conf
#  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/{{ APP_NAME }}
#            backup=yes
#
#- name: Schedule log rotation
#  cron: name="rotate {{ APP_NAME }} logs" special_time=hourly
#        job="/usr/sbin/logrotate /etc/logrotate.d/{{ APP_NAME }}"


